server:
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/inventorydb
    username: root
    password: winny@1717
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
