server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Auth Service
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**

        # Inventory Service
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/**

        # Order Service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**

        # Swagger/OpenAPI forwarding
        - id: auth-swagger
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth, /v3/api-docs

        - id: inventory-swagger
          uri: lb://inventory-service
          predicates:
            - Path=/v3/api-docs/inventory
          filters:
            - RewritePath=/v3/api-docs/inventory, /v3/api-docs

        - id: order-swagger
          uri: lb://order-service
          predicates:
            - Path=/v3/api-docs/order
          filters:
            - RewritePath=/v3/api-docs/order, /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: your-super-secret-key

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /v3/api-docs/auth
      - name: Inventory Service
        url: /v3/api-docs/inventory
      - name: Order Service
        url: /v3/api-docs/order

